import img1 from "../assets/OthersImg/AYA DE YOPOUGON TOME 1.jpg"
import img2 from "../assets/OthersImg/AYA DE YOPOUGON TOME 2.jpg"
import img3 from "../assets/OthersImg/LE PETIT PRINCE.jpg"
import img4 from "../assets/OthersImg/SARRAOUNIA.jpg"
import img5 from "../assets/OthersImg/LES FRASQUES D'EBINTO.jpg"
import img6 from "../assets/OthersImg/LE CAHIER NOIR.jpg"
import img7 from "../assets/OthersImg/PERE RICHE PERE PAUVRE.jpg"
import img8 from "../assets/OthersImg/STENDHAL ET LE COMIQUE.jpg"
import img9 from "../assets/OthersImg/TROIS PRETENDANTS... UN MARI.jpg"
import img10 from "../assets/OthersImg/YULU.png"
import img11 from "../assets/OthersImg/LA BOMBE AFRICAINE.jpg"
import img12 from "../assets/OthersImg/LA COLERE DES AVORTES.jpg"
import img13 from "../assets/OthersImg/LA FERME DES ANIMAUX.png"
import img14 from "../assets/OthersImg/LE MIROIR DES MUSES.jpg"
// import img15 from "./OthersImg/MEMOIRES DE LA FORET.png"
import img16 from "../assets/OthersImg/SUR L'ESTHETIQUE LITTERAIRE NEGRO-AFRICAINE.jpg"
// import img17 from "./OthersImg/L'HOMME AUX CHAUSSETTES ROUGES.jpg"
// import img18 from "./OthersImg/LE PLEURER-RIRE.PNG"
import img19 from "../assets/OthersImg/JUSQU'AU SEUIL DE L'IRREEL.jpg"
// import img20 from "./OthersImg/BETES DE SCENE.jpg"
import img21 from "../assets/OthersImg/ICEBREAKER.png"
import img22 from "../assets/OthersImg/L'AMOUR AU TEMPS DU CORONA.jpg"
// import img23 from "./OthersImg/L'AFRIQUE AU SECOURS DE L'AFRIQUE.jpg"
import img24 from "../assets/OthersImg/JEFFERSON.png"
import img25 from "../assets/OthersImg/ARROGANT COMME UN FRANCAIS EN AFRFIQUE.PNG"
import img26 from "../assets/OthersImg/EN ATTENDANT LE VOTE DES BETES SAUVAGES.jpg"
import img27 from "../assets/OthersImg/IL N'Y A PAS DE PETITE QUERELLE.jpg"
import img28 from "../assets/OthersImg/LA POUSSE-POUSSE DE MAKELEKELE.jpg"
import img30 from "../assets/OthersImg/NTRODUCTION AUX LITTERATURES FRANCOPHONES.jpg"
import img31 from "../assets/OthersImg/LE COMIQUE ECONOMIQUE.jpg"
import img32 from "../assets/OthersImg/L'AVENTURE AMBIGUE.jpg"
import img33 from "../assets/OthersImg/FREDERIC MISTRAL , L'OMBRE ET L'ECHO.png"

export const Data = [
    {
        id:1,   
        name:'AYA DE YOPOUGON TOME 1',
        prix:"5000",
        annees: 2011,
        img: img1,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:2,   
        name:'AYA DE YOPOUGON TOME 2',
        prix:"6500",
        annees: 2012,
        img: img2,
        desc:" Lorem  "
    },
    {
        id:3,   
        name:'LE PETIT PRINCE',
        prix:"3500",
        annees: 2014,
        img: img3,
        desc:" le petit prince est Oeuvre d'aventure ou le petit prince parcour les planets pour empecher au serpent un acteur de faire du mal et en meme temps il desire rejoindre sa rose sa bien aime",
    },
    {
        id:4,   
        name:'SARRAOUNIA',
        prix:"3500",
        annees: 2016,
        img: img4,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:5,   
        name:"LES FRASQUES D'EBINTO",
        prix:"3500",
        annees: 2015,
        img: img5,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:6,   
        name:'LE CAHIER NOIR',
        prix:"3500",
        annees: 2014,
        img: img6,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:7,   
        name:'PERE RICHE PERE PAUVRE',
        prix:"8000",
        annees: 2018,
        img: img7,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:8,   
        name:'STENDHAL ET LE COMIQUE',
        prix:"4000",
        annees: 2015,
        img: img8,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:9,   
        name:'TROIS PRETENDANTS UN MARI',
        prix:"5000",
        annees: 2020,
        img: img9,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:10,   
        name:'YULU',
        prix:"4500",
        annees: 2022,
        img: img10,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:11,   
        name:'LA BOMBE AFRICAINE',
        prix:"4500",
        annees: 2010,
        img: img11,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:12,   
        name:'LA COLERE DES AVORTES',
        prix:"4000",
        annees: 2022,
        img: img12,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:13,   
        name:'LA FERME DES ANIMAUX',
        prix:"4000",
        annees: 2018,
        img: img13,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:14,   
        name:'LE MIROIR DES MUSES',
        prix:"4500",
        annees: 2022,
        img: img14,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    // {
    //     id:15,   
    //     name:'MEMOIRES DE LA FORET',
    //     prix:"3500",
    //     annees: 2020,
    //     img: img15,
    //     desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    // },
    {
        id:16,   
        name:"SUR L'ESTHETIQUE LITTERAIRE NEGRO-AFRICAINE",
        prix:"4500",
        annees: 2018,
        img: img16,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    // {
    //     id:17,   
    //     name:"L'HOMME AUX CHAUSSETTES ROUGES",
    //     prix:"15000",
    //     annees: 2022,
    //     img: img17,
    //     desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    // },
    // {
    //     id:18,   
    //     name:'LE PLEURER-RIRE',
    //     prix:"4500",
    //     annees: 2007,
    //     img: img18,
    //     desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    // },
    {
        id:19,   
        name:"JUSQU'AU SEUIL DE L'IRREEL",
        prix:"3500",
        annees: 2022,
        img: img19,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    // {
    //     id:20,   
    //     name:'BETES DE SCENE',
    //     prix:"4500",
    //     annees: 2015,
    //     img: img20,
    //     desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    // },
    {
        id:21,   
        name:'ICEBREAKER',
        prix:"4500",
        annees: 2021,
        img: img21,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:22,   
        name:"L'AMOUR AU TEMPS DU CORONA",
        prix:"3500",
        annees: 2020,
        img: img22,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    // {
    //     id:23,   
    //     name:"L'AFRIQUE AU SECOURS DE L'AFRIQUE",
    //     prix:"4000",
    //     annees: 2018,
    //     img: img23,
    //     desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    // },
    {
        id:24,   
        name:'JEFFERSON',
        prix:"5000",
        annees: 2017,
        img: img24,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:25,   
        name:'ARROGANT COMME UN FRANCAIS EN AFRFIQUE',
        prix:"5000",
        annees: 2017,
        img: img25,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:26,   
        name:'EN ATTENDANT LE VOTE DES BETES SAUVAGES',
        prix:"8000",
        annees: 2019,
        img: img26,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:27,   
        name:"IL N'Y A PAS DE PETITE QUERELLE",
        prix:"4000",
        annees: 2013,
        img: img27,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:28,   
        name:'LA POUSSE-POUSSE DE MAKELEKELE',
        prix:"3500",
        annees: 2020,
        img: img28,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:29,   
        name:'INTRODUCTION AUX LITTERATURES FRANCOPHONES',
        prix:"8000",
        annees: 2013,
        img: img30,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:30,   
        name:'LE COMIQUE ECONOMIQUE',
        prix:"5000",
        annees: 2014,
        img: img31,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:31,   
        name:"L'AVENTURE AMBIGUE",
        prix:"3000",
        annees: 2015,
        img: img32,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    {
        id:32,   
        name:"FREDERIC MISTRAL , L'OMBRE ET L'ECHO",
        prix:"8000",
        annees: 2019,
        img: img33,
        desc:" Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ab assumenda "
    },
    
]
